ALTER TABLE runs ADD COLUMN input_tokens INTEGER NOT NULL DEFAULT 0;
ALTER TABLE runs ADD COLUMN output_tokens INTEGER NOT NULL DEFAULT 0;
ALTER TABLE runs ADD COLUMN cache_read_tokens INTEGER NOT NULL DEFAULT 0;
ALTER TABLE runs ADD COLUMN cache_creation_tokens INTEGER NOT NULL DEFAULT 0;
